upstream_widget: http://web-widget-oversea-cn-hongkong.oss-cn-hongkong-internal.aliyuncs.com

main_nginx_upstreams:
  s3-proxy:
    # minio-gateway
    servers:
      - addr: 10.131.1.160:80

  backend-standard-api-uwsgi:
    servers:
      - addr: 10.131.1.157:5001

  backend-visit-api-uwsgi:
    servers:
      - addr: 10.131.1.159:5001

  backend-slow-api-uwsgi:
    servers:
      - addr: 10.131.1.156:5001

  app-upload:
    # fileshelf
    servers:
      - addr: 10.131.1.158:80

  workbench:
    servers:
      - addr: 10.131.1.140:80

  bulletin-pull:
    servers:
      - addr: 10.131.1.154:80

  hotchpotch:
    servers:
      - addr: 10.131.1.153:80

  diplomat:
    servers:
      - addr: 10.131.1.161:80

  facade-api:
    servers:
      - addr: 10.131.1.139:9999

  throttle:
    servers:
      - addr: 10.131.1.151:80

  api-datagateway:
    servers:
      - addr: 10.119.8.189:80

  herald:
    servers:
      # FIXME: 还没有部署
      - addr: 10.119.8.186:80
